spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/siptis
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect

cloud:
    aws:
      region:
        static: sa-east-1
      stack:
        auto: false
      credentials:
        access-key: AKIA4O3PHN4JLLTTCSW5
        secret-key: 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

logging:
  level:
    com:
      amazonaws:
        util:
          EC2MetadataUtils: error