spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/siptis
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  servlet:
    multipart:
      enabled: true
      max-file-size: 50MB
      max-request-size: 50MB

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  mail:
    host: smtp.gmail.com
    username: maury.vargasl@gmail.com
    password: ujlfeavaprrvlmxs
    properties.mail.smtp:
      auth: true
      ssl.enable: true
      ssl.required: true
      ssl.trust: smtp.gmail.com



server:
  port: 9090

cloud:
    aws:
      region:
        static: sa-east-1
      stack:
        auto: false
      credentials:
        access-key: AKIA4O3PHN4JLLTTCSW5
        secret-key: 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

logging:
  level:
    com:
      amazonaws:
        util:
          EC2MetadataUtils: error


