spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/siptis2
    username: postgres
    password: serrano123
    driver-class-name: org.postgresql.Driver
  servlet:
    multipart:
      enabled: true
      max-file-size: 50MB
      max-request-size: 50MB

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  mail:
    host: smtp.gmail.com
    port: 587
    username: siptis.umss@gmail.com
    password: ftryberzfpkddfvj
    properties.mail:
      smtp:
        auth: true
        ssl.trust: smtp.gmail.com
        starttls.enable: true
      debug: true



server:
  port: 9090

cloud:
  aws:
    region:
      static: sa-east-1
    stack:
      auto: false
    credentials:
      access-key: AKIA4O3PHN4JMSTAYYPK
      secret-key: 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

logging:
  level:
    com:
      amazonaws:
        util:
          EC2MetadataUtils: error


