spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/siptis
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  servlet:
    multipart:
      enabled: true
      max-file-size: 50MB
      max-request-size: 50MB

  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  mail:
    host: smtp.gmail.com
    username: maury.vargasl@gmail.com
    password: ujlfeavaprrvlmxs
    properties.mail.smtp:
      auth: true
      ssl.enable: true
      ssl.required: true
      ssl.trust: smtp.gmail.com



server:
  port: 9090

cloud:
  aws:
    region:
      static: sa-east-1
    stack:
      auto: false
    credentials:
      access-key: AKIA4O3PHN4JMSTAYYPK
      secret-key: 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

logging:
  level:
    com:
      amazonaws:
        util:
          EC2MetadataUtils: error
    org:
      springframework:
        web:
          client:
            RestTemplate: DEBUG

openai:
  api:
    url: https://api.openai.com/v1/chat/completions
    key: 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
  model: gpt-3.5-turbo
