package backend.siptis.commons;

public enum MensajeServicio {
    SIN_PROYECTOS, SIN_PRESENTACIONES, ID_NO_EXISTE, NOT_FOUND, ERROR, NO_FILE_ATTACHED,
    OPERACION_DE_NUBE_COMPLETADA, OK,
    PRESENTACION_ELIMINADA, PRESENTACION_REVISADA, PRESENTACION_PENDIENTE, PRESENTACION_CREADA, PRESENTACION_ENTREGADA
}

