package backend.siptis.commons;

public enum ServiceMessage {
    NO_PROJECTS,
    WITHOUT_PROJECTS, OK, ID_DOES_NOT_EXIST, NOT_FOUND,
    PRESENTATION_CREATED, PENDING_PRESENTATION, PRESENTATION_DELETED ,CLOUD_OPERATION_COMPLETE, ERROR,
    NO_PRESENTATIONS, NO_FILE_ATTACHED,
    DOCUMENT_GENERATED, NO_DOCUMENTS, DOCUMENT_DELETED,
    EMAIL_NOT_EXIST, INVALID_TOKEN,
    PROJECT_ID_DOES_NOT_EXIST, USER_ID_DOES_NOT_EXIST, ID_REVIEWER_DOES_NOT_MATCH_WITH_PROJECT, THERE_IS_NO_PRESENTATION_YET, PROJECT_HAS_ALREADY_BEEN_ACCEPTED, PROJECT_IS_ALREADY_NOT_ACCEPTED, PROJECT_IS_ON_ANOTHER_PHASE, PRESENTACION_REVISADA,
    ERROR_REGISTER_ACCOUNT,ERROR_REGISTER_ACCOUNT_EMAIL, ERROR_REGISTER_ACCOUNT_CI,
    ERROR_REGISTER_ACCOUNT_NAMES, ERROR_REGISTER_ACCOUNT_LASTNAMES, ERROR_REGISTER_ACCOUNT_CEL_NUMBER,
    ERROR_REGISTER_ACCOUNT_CODSIS, ERROR_REGISTER_ACCOUNT_BIRTH_DATE, ERROR_REGISTER_ACCOUNT_PASSWORD,
    ERROR_LOG_IN, ERROR_BAD_CREDENTIALS, USER_IS_NOT_A_TRIBUNAL, PROJECT_HAS_ALREADY_A_DEFENSE_DATE, ID_PLACE_DOES_NOT_EXIST, THERE_IS_ANOTHER_RESERVATION_TOO_CLOSE, ID_TRIBUNAL_DOES_NOT_MATCH_WITH_PROJECT, DEFENSE_HAS_NOT_STARTED, DEFENSE_HAS_FINISHED, SCORE_IS_NOT_VALID, THERE_IS_A_PROBLEM_WITH_THE_CLOUD,
    USER_DELETED, USER_AREA_DELETED, AREA_DELETED, ERROR_CANNOT_DELETE_USER,
    ERROR_VALIDATION,
    SEMESTER_STARTED, SEMESTER_ENDED, MONTH_NUMBER_NOT_VALID, SEMESTER_DATE_EDITED
}

