package backend.siptis.commons;

public enum ServiceMessage {
    WITHOUT_PROJECTS, OK, ID_DOES_NOT_EXIST, NOT_FOUND,
    PRESENTACION_CREADA, PRESENTACION_PENDIENTE, PRESENTACION_ELIMINADA ,
    PRESENTACION_ENTREGADA, OPERACION_DE_NUBE_COMPLETADA, ERROR,
    SIN_PRESENTACIONES,
    SIN_PROYECTOS,  ID_NO_EXISTE,  NO_FILE_ATTACHED,
    ID_PROJECT_DOES_NOT_EXIST, ID_USER_DOES_NOT_EXIST, ID_REVIEWER_DOES_NOT_MATCH_WITH_PROJECT, PRESENTACION_REVISADA
}

