package BackendSIPTIS.commons;

public enum MensajeServicio {
    SIN_PROYECTOS, OK, ID_NO_EXISTE, NOT_FOUND,
    PRESENTACION_CREADA, PRESENTACION_PENDIENTE, PRESENTACION_ELIMINADA ,
    PRESENTACION_ENTREGADA, OPERACION_DE_NUBE_COMPLETADA, ERROR,
    SIN_PRESENTACIONES,
}

